include/fc/io/enum_type.hpp
- operator> copy/paste error.
- Added explicit to constructors.
=> Fix operator>

src/network/http/http_client.cpp
the HTTP Host header can omit a port IFF the port in question is the default port for the protocol.  The http client was not respecting this nuance and was omitting the port at all times.
=> proper HTTP Host header for non-standard ports

src/crypto/signature.cpp
See https://github.com/EOSIO/eos/issues/4214
=> Add rethrow to provide better error for malformed signature.

src/network/http/http_client.cpp
merge #24 and #25 into master as well
=> Fix rfc2818 Port to master

CMakeLists.txt
This is causing too much grief for now. EOSIO/eos#6381
=> Rollback cmake changes

src/compress/miniz.c, src/crypto/aes.cpp, src/crypto/elliptic_common.cpp, src/crypto/elliptic_r1.cpp, src/log/log_message.cpp
Try to silence most GCC 7 warnings
=> Fix gcc warnings

include/fc/network/message_buffer.hpp
- Create a version of message_buffer datastream adapter that peeks instead of reads
- Unittest added in eos repo
=> Add peek datastream adapter

include/fc/uint128.hpp
Fix bug in uint128 bitwise OR operator
=> Fix bitwise OR operator for uint128

include/fc/log/logger_config.hpp, src/log/logger_config.cpp
- For linux
-- Add ability to set os thread name 
-- Use os thread name in logging
=> Add ability to set thread name and use that in logging

src/network/http/http_client.cpp, vendor/websocketpp/websocketpp/transport/asio/connection.hpp, vendor/websocketpp/websocketpp/transport/asio/endpoint.hpp, vendor/websocketpp/websocketpp/transport/asio/security/none.hpp, vendor/websocketpp/websocketpp/transport/asio/security/tls.hpp
- Changes needed for boost 1.70.0.
=> Update for boost 1.70.0

src/network/http/http_client.cpp, vendor/websocketpp/websocketpp/transport/asio/connection.hpp, vendor/websocketpp/websocketpp/transport/asio/endpoint.hpp, vendor/websocketpp/websocketpp/transport/asio/security/none.hpp, vendor/websocketpp/websocketpp/transport/asio/security/tls.hpp
- Changes needed for boost 1.70.0.
=> Update for boost 1.7.0 - v1.8.x

include/fc/exception/exception.hpp, src/exception.cpp
Added a wrapper class for std::exception.  Modified macros to use new wrapper.
=> added wrapper for std::exception

src/crypto/elliptic_webauthn.cpp
Co-Authored-By: Matt Witherspoon <32485495+spoonincode@users.noreply.github.com>
=> use rapidjson's iterative mode to parse webauthn json

include/fc/crypto/base58.hpp, include/fc/crypto/common.hpp, include/fc/crypto/private_key.hpp, include/fc/crypto/public_key.hpp, include/fc/crypto/signature.hpp, include/fc/exception/exception.hpp, include/fc/time.hpp, include/fc/variant.hpp, src/crypto/base58.cpp, src/crypto/elliptic_common.cpp, src/crypto/elliptic_r1.cpp, src/crypto/private_key.cpp, src/crypto/public_key.cpp, src/crypto/signature.cpp, test/crypto/test_cypher_suites.cpp
Co-Authored-By: Kevin Heifner <heifnerk@objectcomputing.com>
=> Add deadline to base58 encoding.

include/fc/io/cfile.hpp
Added sync method to provide fsync functionality and added mode constants.
=> Adding fsync and adding constants for modes.

include/fc/io/json.hpp, src/io/json.cpp, src/variant.cpp, test/io/CMakeLists.txt, test/io/test_json.cpp, test/variant/test_variant.cpp
Issue #8741,
Merge FC submodule PR 144 and PR 145 from master to v2.0.x. 
change files are:
1. include/fc/io/json.hpp
2. src/io/json.cpp
3. test/io/CMakeLists.txt
4. test/io/test_json.cpp
5. test/variant/test_variant.cpp
6. src/io/variant.cpp
=>  merge changes from pr 144 and pr145 from master to v2.0.x

test/io/CMakeLists.txt
Correct the test command names for CI
=> correct the command name for test cases

include/fc/io/json.hpp, src/io/json.cpp, src/log/gelf_appender.cpp, src/variant.cpp, test/io/test_json.cpp
add enum class to  parse_type and output_formatting and swap the size limitation after deadline
=> add enum class to parse_type and output_formatting

include/fc/io/json.hpp, src/io/json.cpp, src/log/gelf_appender.cpp, src/variant.cpp, test/io/CMakeLists.txt, test/io/test_json.cpp
Merge the changes on PR 147 and PR150 from master to v2.0.x
=> Merge files from PR 147 and PR150 from master

CMakeLists.txt, include/fc/log/dmlog_appender.hpp, include/fc/log/logger.hpp, src/log/appender.cpp, src/log/dmlog_appender.cpp, src/log/logger_config.cpp
Ping @heifner 
Linked with EOSIO/eos#8788
=> Extract of deep mind logger in libraries/fc directly

src/exception.cpp
Fix for potential infinite loop. 
Thanks:  abitmore <abitmore@users.noreply.github.com>
See: https://github.com/bitshares/bitshares-fc/pull/193
=> Exception to_detail_string fix - 2.0

src/exception.cpp
Fix for potential infinite loop. 
Thanks:  abitmore <abitmore@users.noreply.github.com>
See: https://github.com/bitshares/bitshares-fc/pull/193
=> Exception to_detail_string fix.

include/fc/io/json.hpp, include/fc/utf8.hpp, src/io/json.cpp, src/utf8.cpp, src/variant.cpp
Consolidated Security Fixes for 1.8.14
- Escape Unicode C1 control code points.
Co-Authored-By: Kevin Heifner heifnerk@objectcomputing.com
=> Consolidated Security Fixes for 1.8.14

include/fc/io/json.hpp, include/fc/utf8.hpp, src/io/json.cpp, src/utf8.cpp, src/variant.cpp, test/io/test_json.cpp
Consolidated Security Fixes for 2.0.6
- Escape Unicode C1 control code points.
Co-Authored-By: Kevin Heifner heifnerk@objectcomputing.com
=> Consolidated Security Fixes for 2.0.6

include/fc/io/json.hpp, include/fc/utf8.hpp, src/io/json.cpp, src/utf8.cpp, src/variant.cpp, test/io/test_json.cpp
Consolidated Security Fixes for develop
- Escape Unicode C1 control code points.
Co-Authored-By: Kevin Heifner heifnerk@objectcomputing.com
=> Consolidated Security Fixes for develop
