EOSIO/fc

include/fc/crypto/elliptic_r1.hpp
src/crypto/elliptic_r1.cpp

There is code buried in the R1 signing code that takes the r & s from a ECDSA signature, figures out which one of the 4 solutions goes with the given public key, and creates the 65 byte signature blob used in eosio
Break this code out so it is callable outside of r1::private_key class. We need this same logic when processing signatures from sources other than the r1::private_key class, like from hardware signers.
No functionality changes. Work on EOSIO/eos#2252

Break out R1 signature compaction

---

include/fc/io/varint.hpp

The templated operator conversion allowed:
```
unsigned_int i = 5;
void foo(fc::microseconds us);
foo(i);
```

Remove templated operator conversion to avoid unintended conversions

---

src/crypto/sha256.cpp

- Optimize operator == and != of sha256 which are heavly used.
- Idea from: https://lemire.me/blog/2018/08/22/avoid-lexicographical-comparisons-when-testing-for-string-equality

Optimize sha256 comparison

---

.gitmodules
CMakeLists.txt
secp256k1/CMakeLists.txt
secp256k1/libsecp256k1-config.h

Bundle our secp256k1 library as a submodule. This removes one external dependency (making it a little easier for packaging and future updates), makes the build of secp256k1 use same compiler & flags as the main applications, and fixes a bug where the configure script on macOS wasn’t enabling x86_64 asm operations.

Build secp256k1 as a submodule

---

include/fc/static_variant.hpp

This is to ensure that passing a non-const reference to the constructor does not ever call the forwarding reference constructor (I seems like I somehow ran into this issue with the Ubuntu 16.04 compiler).

delegate static_variant non-const reference constructor to const reference constructor

---

CMakeLists.txt
include/fc/network/platform_root_ca.hpp
src/network/LICENSE.go
src/network/http/http_client.cpp
src/network/platform_root_ca.cpp

Add a method that can be used within fc’s http_client as well as cleos to populate the HTTPS trusted root certificates based on the system certificate store.
This does pose a behavior change for http_client (used within producer_plugin): previously it trusted no root CAs other then the one provided by the user. Now it will trust the system cert store.
Much of the logic to implement this function was taken from golang’s lib. I’ve included their license file.

On macOS populate root CAs via system cert store

---

include/fc/variant.hpp

On my clang7, boost 1.68, gnuc++ 8.2.1 environment this line failed to compile. Unknown which of the aforementioned differences may be responsible.
```
/home/spoon/eos/src/libraries/fc/include/fc/variant.hpp:654:11: error: no matching conversion for functional-style cast from 'const boost::multiprecision::number<cpp_
int_backend<128, 128, boost::multiprecision::unsigned_magnitude, boost::multiprecision::unchecked, void> >' to 'std::string' (aka 'basic_string<char>')               
v = std::string(n);                                                                                                                                             
^~~~~~~~~~~~~               
/home/spoon/eos/src/libraries/fc/include/fc/variant.hpp:584:7: note: in instantiation of function template specialization …
```

Fix boost mp num compile error

---

src/time.cpp

This fixes two issues:
1. time_points which were more than 32bits of seconds from the epoch would wrap due to the silent integer narrowing that happens in `uint32_t time_point::sec_since_epoch() const` as a result those time points would translate to the wrong ISO string.
2. negative time_points are representable due to being composed of the `fc::microsecond` type which can store negative values.  However, these have no representable ISO string so they now degrade to a duration in terms of seconds with 3-digits of precision for millisecond output.  Effectively providing the same base unit as the ISO string (seconds) and the extra resolution.
Note: it is probably worthwhile to consider if changing `::sec_since_epoch() const` and removing the express-ability of negative points in time is …

Fix time_point to string conversion for large and negative values

---

src/log/console_appender.cpp

When logging to the systemd journal prepend the syslog priority tag. This lets the journal be aware of the log level of each message thus allowing the built-in filtering and coloring to work.

Prepend syslog priority when logging to systemd journal

---

include/fc/io/raw.hpp
include/fc/reflect/reflect.hpp
include/fc/reflect/variant.hpp

- Call the optional verifier on reflected unpacked types
- Added `has_feature_reflector_verify_on_unpacked_reflected_types`  trait to `fc::raw` so users of `fc::raw::unpack` can depend on this feature.
- This allows classes like the newly refactored `packed_transaction` to perform "construction" needed operations after unpacking.
- Also added missing call to verify for the non-static version of the reflect `visit`.

Add verifier call to raw unpack

---

include/fc/io/raw.hpp
include/fc/reflect/reflect.hpp
include/fc/reflect/variant.hpp

- Fix for reflector_init not being called
- private inheritance and const/non-const causing SFINAE to kick in when not desired
- to/from variant was not calling `reflector_init()`
- Explicit call to `reflector_init()` no longer needed for `raw` `fc` `unpack_object_visitor`
Co-authored-by: arhag [arhag@users.noreply.github.com](mailto:arhag@users.noreply.github.com)

Fix for reflector_init

---

include/fc/reflect/reflect.hpp

- For FC_REFLECT_DERIVED types reflector_init was being called multiple times on the derived type. All but the last was before all the members had been serialized.
- Added tag type `reflect_init` that derived types can derive from to indicate `reflector_init()` should be called.
- Added `static_assert` to indicate if reflected type derives from tag type `reflect_init` that they also provide the `reflector_init()` method.
- Added `static_assert` to indicate if `reflector_init()` provided that reflected type should be derived from `reflect_init`.
- Unittest added to eos repo

Fix for reflector_init being called multiple times

---

include/fc/log/log_message.hpp
include/fc/string.hpp
src/log/log_message.cpp
src/variant.cpp

- Provide a `log_message::get_limited_message()` that does minimal work to format a log message to optimize logging.
- `get_limit_message` implemented by adding a minimize option to `variant` `format_string`

Optimize error logging

---

src/log/log_message.cpp

- Fix warning, return "unknown" for invalid log_level in `to_string`
- Resolves #69

Fix warning, return unknown for invalid log_level

---

include/fc/container/container_detail.hpp
include/fc/utility.hpp

The improved utility functions now use the standard `std::uses_allocator` rather than my own custom heuristic. These changes should now support sets of tuples.
The container_detail.hpp implementation is modified to use these new utility functions.

improve utility functions to construct types optionally with allocators

---

src/crypto/aes.cpp

this deviously hidden code probably needs to be moved to openssl.cpp so we keep all the openssl initialization rigmarole in a single location. Also, it should be ifdef'ed out for openssl 1.1. But I'm not doing that just yet due to being so close to 1.8 release

Removing lingering boost::mutex usage from openssl thread support

---

include/fc/time.hpp

- Remove error prone `time_point::operator+` and `time_point_sec::operator+=` and `time_point_sec::operator-=`
- today@1pm + today@1pm == year4038  <= clearly not what is expected
- today@5pm - today@4pm == year1970 <= clearly not what is expected

Remove error prone operators

---

CMakeLists.txt

This part of fc's cmake clearly tried to link openssl -- and its zlib dep -- statically. Unfortunately it's clear this doesn't always work: see the ubuntu 18 binaries we've distributed, they have openssl and zlib dynamically linked. But even worse, dynamic vs static seems to be somewhat indeterministic; I saw it switch from dynamic to static on one of my build environments with no explanation.
Let's remove this for now and always link dynamic.
For .debs and .rpms we already indicate we need openssl and zlib as deps (actually the rpm is missing the zlib dep but the openssl-libs package it will get via openssl has a zlib dep).
For mac, we already indicate in our bottle that openssl is required. zlib is system provided.

No longer try and static link openssl (and zlib)

---

include/fc/variant_object.hpp

Issue seen on GCC 7 -std=c++1z
Fix by @heifner

Make sure mutable_variant_object's templated constructor doesn't get called to make a copy

---

include/fc/variant_object.hpp

Make sure mutable_variant_object's templated constructor doesn't get called to make a copy.
Issue seen on GCC 7 -std=c++1z

mutable_variant_object fix for GCC 7 - v1.6.x

---

include/fc/variant_object.hpp

Make sure mutable_variant_object's templated constructor doesn't get called to make a copy.
Issue seen on GCC 7 -std=c++1z

mutable_variant_object fix for GCC 7 - v1.7.x

---

include/fc/variant_object.hpp
src/variant_object.cpp
test/CMakeLists.txt
test/variant/CMakeLists.txt
test/variant/test_variant.cpp

Follow-up to #83 
Also cleans up some comments and whitespace in variant_object.hpp

mutable_variant_object: chained operations should preserve rvalueness

---

include/fc/static_variant.hpp

This PR removes the need to have a typename member named  `result_type` as part of a visitor for `::visit`.  Instead, it will deduce the type that results from the appropriate `operator()` invocation and enforce that all possible invocations result in the same type.   Types are separated by input `const`-ness so it is legal for `::operator() (const T&)` and `::operator() (T&)` to return different types so long as all possible T's return the same thing in each case.  
Note: this PR does not clean up visitors declared/used in the rest of FC's code base that currently declare a `result_type`

add support for lambdas as visitors to fc::static_variants

---

include/fc/static_variant.hpp
test/CMakeLists.txt
test/static_variant/CMakeLists.txt
test/static_variant/test_static_variant.cpp

Previously `fc::static_variant` has implementations of `operator ==` and `operator <` that only compared the type information and did not compare the enclosed values. 
This PR adds type information that detects whether all of the constituent types support various standard operator functions (including when supported through constructs like `std::is_equal` rather than a plain `operator ==` for instance).  
This type information is used to control visibility of the operators which compare the type discriminator and when equal compare the enclosed values.  These operators are only present when ALL constituent types support some form of the operator:
supported operators:
- `operator ==`
- `operator !=`
- `operator <`
- `operator <=`
- `operator >`
- `operator >=`

add/fix support for comparison operators to static_variant 

---

src/network/platform_root_ca.cpp

When a certificate has no trust settings it is to be trusted
See https://developer.apple.com/documentation/security/1400261-sectrustsettingscopytrustsetting?language=objc
>An empty trust settings array (that is, the trustSettings parameter returns a valid but empty CFArray) means "always trust this certificate” with an overall trust setting for the certificate of kSecTrustSettingsResultTrustRoot. Note that an empty trust settings array is not the same as no trust settings (the trustSettings parameter returns NULL), which means "this certificate must be verified to a known trusted certificate”.

Fix certificate trust when trust settings is empty

---

include/fc/log/appender.hpp
include/fc/log/logger.hpp
include/fc/log/logger_config.hpp
src/log/appender.cpp
src/log/console_appender.cpp
src/log/gelf_appender.cpp
src/log/logger.cpp
src/log/logger_config.cpp

- Enabling feature of updating log config during running process (nodeos) caused SEGFAULT since the logging configuration is not thread safe.
- Add `mutex` around logging configuration and around `logger.log`
- Remove mutexs in `gelf_appender` and `console_appender` since the higher level `mutex` will protect the entire call.
- Moved `appender_factory_map`, `appender_map`, and `logger_map` to a `log_config` class to encapsulate initialization and access.

Thread safe log config

---

include/fc/log/appender.hpp
include/fc/log/logger.hpp
include/fc/log/logger_config.hpp
src/log/appender.cpp
src/log/console_appender.cpp
src/log/gelf_appender.cpp
src/log/logger.cpp
src/log/logger_config.cpp

- Enabling feature of updating log config during running process (nodeos) caused SEGFAULT since the logging configuration is not thread safe.
- Add `mutex` around logging configuration and around `logger.log`
- Remove mutexs in `gelf_appender` and `console_appender` since the higher level `mutex` will protect the entire call.
- Moved `appender_factory_map`, `appender_map`, and `logger_map` to a `log_config` class to encapsulate initialization and access.

Thread safe log config - v1.8.x

---

src/log/logger_config.cpp

- Revert to leaking loggers on exit to fix shutdown issue

Revert to log_config dynamic allocation

---

src/log/logger_config.cpp

- Revert to leaking loggers on exit to fix shutdown issue

Revert to log_config dynamic allocation - 1.8.x

---

include/fc/log/appender.hpp
include/fc/log/logger.hpp
include/fc/log/logger_config.hpp
src/log/appender.cpp
src/log/console_appender.cpp
src/log/gelf_appender.cpp
src/log/logger.cpp
src/log/logger_config.cpp

- Enabling feature of updating log config during running process (nodeos) caused SEGFAULT since the logging configuration is not thread safe.
- Add `mutex` around logging configuration and around `logger.log`
- Remove mutexs in `gelf_appender` and `console_appender` since the higher level `mutex` will protect the entire call.
- Moved `appender_factory_map`, `appender_map`, and `logger_map` to a `log_config` class to encapsulate initialization and access.
- Includes fix of https://github.com/EOSIO/fc/pull/102 for v1.7.x

Thread safe log config - 1.7.x

---

include/fc/log/logger.hpp
src/log/logger_config.cpp

- Modify `logger_config::update_logger` to setup a logger with the default logger if no `logging.json` is provided.
- This will make non-default loggers have a default log level of the default logger, currently that is `info`.

Provide default log level of info for non-configured loggers.

---

src/variant.cpp

Used for https://github.com/EOSIO/eos/pull/7530

Use boost multiprecision string representation for uint128 and int128 variant

---

include/fc/scoped_exit.hpp
test/CMakeLists.txt
test/scoped_exit/CMakeLists.txt
test/scoped_exit/test_scoped_exit.cpp

There are two problems with it:
- ~scoped_exit() is intended to call the destructor, but it
is actually parsed as a complement operator + default constructor.
- An explicit destructor call ends the lifetime of the object,
which makes further use of it undefined behavior.
This function is definitely unused, because it doesn't compile.

Remove incorrect move assignment operator from scoped_exit

---

include/fc/io/raw.hpp
include/fc/io/raw_fwd.hpp
include/fc/variant.hpp

Add support for `boost::container::deque` to `pack/unpack/to_variant/from_variant`.

Add supprt for boost deque

---

src/log/logger_config.cpp

unordered_map::operator[] creates a value inititalized element
if the key isn't present.  This breaks initialize_appenders, which
expects appender_map to contain only non-null pointers.
This should fix https://github.com/EOSIO/eos/issues/2380

Fix crash when using using a bad appender.

---

include/fc/network/message_buffer.hpp
test/CMakeLists.txt
test/network/CMakeLists.txt
test/network/test_message_buffer.cpp

boost::object_pool is not thread-safe.  Use singleton_pool instead.  This should address https://github.com/EOSIO/eos/issues/8290.

Fix race in message_buffer.

---

include/fc/exception/exception.hpp
include/fc/io/json.hpp
include/fc/io/raw_variant.hpp
include/fc/time.hpp
include/fc/variant.hpp
src/exception.cpp
src/io/json.cpp
src/log/gelf_appender.cpp
src/log/logger.cpp
src/network/http/http_client.cpp
src/variant.cpp

- Added `deadline` to `json::to_string`
- Added new `FC_CHECK_DEADLINE` macro
- Modified `logger::log` to not throw exceptions
- Added `blob_type` support to variant pack/unpack
- Made `time_point` methods `constexpr`

json::to_string deadline - 1.8

---

include/fc/exception/exception.hpp
include/fc/io/json.hpp
include/fc/io/raw_variant.hpp
include/fc/time.hpp
include/fc/variant.hpp
src/exception.cpp
src/io/json.cpp
src/log/gelf_appender.cpp
src/log/logger.cpp
src/network/http/http_client.cpp
src/variant.cpp

- Added `deadline` to `json::to_string`
- Added new `FC_CHECK_DEADLINE` macro
- Modified `logger::log` to not throw exceptions
- Added `blob_type` support to variant pack/unpack
- Made `time_point` methods `constexpr`

json::to_string deadline - 2.0

---

src/log/logger_config.cpp

unordered_map::operator[] creates a value inititalized element
if the key isn't present.  This breaks initialize_appenders, which
expects appender_map to contain only non-null pointers.

Fix crash when using using a bad appender. - 2.0

---

src/log/logger_config.cpp

unordered_map::operator[] creates a value inititalized element
if the key isn't present.  This breaks initialize_appenders, which
expects appender_map to contain only non-null pointers.

Fix crash when using using a bad appender. - 1.8

---

include/fc/exception/exception.hpp
include/fc/io/json.hpp
include/fc/io/raw_variant.hpp
include/fc/time.hpp
include/fc/variant.hpp
src/exception.cpp
src/io/json.cpp
src/log/gelf_appender.cpp
src/log/logger.cpp
src/network/http/http_client.cpp
src/variant.cpp

- Added `deadline` to `json::to_string`
- Added new `FC_CHECK_DEADLINE` macro
- Modified `logger::log` to not throw exceptions
- Added `blob_type` support to variant pack/unpack
- Made `time_point` methods `constexpr`

json::to_string deadline

---

CMakeLists.txt
src/log/logger_config.cpp

musl, a reasonably popular libc on linux, does not have `pthread_setname_np` & `pthread_getname_np`. Detect presence of these functions before using them.

detect pthread_get/setname_np before usage

---

include/fc/io/json.hpp
src/io/json.cpp
src/variant.cpp
test/io/CMakeLists.txt
test/io/test_json.cpp
test/variant/test_variant.cpp

Issue #8741,
expand limited display for different data types when the minimize flag is set. "..." will be added when the argument limitation is set. The argument limitation is (1024 - format string length) / number of arguments.

Add expansion for data types with minimize flag being set

---

include/fc/crypto/base58.hpp
include/fc/crypto/common.hpp
include/fc/crypto/private_key.hpp
include/fc/crypto/public_key.hpp
include/fc/crypto/signature.hpp
include/fc/io/json.hpp
include/fc/utility.hpp
include/fc/variant.hpp
src/crypto/base58.cpp
src/crypto/elliptic_common.cpp
src/crypto/elliptic_r1.cpp
src/crypto/private_key.cpp
src/crypto/public_key.cpp
src/crypto/signature.cpp

Move to using a yield function instead of a deadline for greater flexibility in determining when to stop processing.

Use yield pattern instead of deadline

---

include/fc/crypto/base58.hpp
include/fc/crypto/common.hpp
include/fc/crypto/private_key.hpp
include/fc/crypto/public_key.hpp
include/fc/crypto/signature.hpp
include/fc/io/json.hpp
include/fc/utility.hpp
include/fc/variant.hpp
src/crypto/base58.cpp
src/crypto/elliptic_common.cpp
src/crypto/elliptic_r1.cpp
src/crypto/private_key.cpp
src/crypto/public_key.cpp
src/crypto/signature.cpp

Move to using a yield function instead of a deadline for greater flexibility in determining when to stop processing.
v2.0.x version of #149

Use yield pattern instead of deadline - 2.0

---

include/fc/static_variant.hpp
test/static_variant/test_static_variant.cpp

This PR allows one to use static_variant as rvalue reference with visitor as follows:
```
static_variant<string, vector<char>> value =...;
std::move(value).visit( overloaded {
[](string&& v) { ...},
[](vector<char>&& v) {...}
} };
```

add rvalue reference support for static_variant

---

CMakeLists.txt
src/crypto/elliptic_webauthn.cpp

... so that any other rapidjson in eosio (or really any other consumer of fc) doesn't suffer from any conflicts

place the rapidjson used for webauthn parsing in to a unique namespace

---

include/fc/io/raw_variant.hpp

Hi, I run a fork of EOSIO that (de-)serializes the `fc::blob` variant_type and came across this error.
The `unpack` function is missing a `return;` in the switch which makes it fall through to the `default` case for the blob variant type. Which then crashes with the `Unknown Variant Type 8` error.

Fix variant type blob unpack bug
